export const UPDATE_ARTIKEL = 'UPDATE_ARTIKEL';
export const GET_ARTIKEL = 'GET_ARTIKEL';
export const UPLOAD = 'UPLOAD';
export const SHOW_ARTIKEL = 'SHOW_ARTIKEL';
export const STORE_ARTIKEL = 'REGISTER_ARTIKEL';
export const UPDATE_ARTIKEL_DONE = 'UPDATE_ARTIKEL_DONE';
